name: Docker Image CI - udagram-api-feed

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        run: |
          docker build -t udagram-api-feed ./udagram-api-feed
          docker tag udagram-api-feed khang610/udagram-api-feed:latest
          docker push khang610/udagram-api-feed:v1
