name: Docker Image CI Frontend
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: udagram-api-frontend
        run: |
          docker build -t udagram-api-frontend ./udagram-frontend
          docker tag udagram-frontend khang610/udagram-frontend:latest
          docker push khang610/udagram-frontend:latest
          