name: Docker Image CI User API
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: udagram-api-user
        run: |
          docker build -t udagram-api-user ./udagram-api-user
          docker tag udagram-api-user khang610/udagram-api-user:latest
          docker push khang610/udagram-api-user:latest
