name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: udagram-reverseproxy
        run: |
          docker build -t udagram-reverseproxy ./udagram-reverseproxy
          docker tag udagram-reverseproxy khang610/udagram-reverseproxy:latest
          docker push khang610/udagram-reverseproxy:latest
